---
validators:
  lineLength:
    enabled: true
    maxLineLength: 72
    subjectMaxLength: 50
  ticketCode:
    enabled: false
  emptyLines:
    enabled: true
    emptyLines: 1
  tags:
    enabled: false
  subjectTense:
    enabled: true
  subjectPeriod:
    enabled: false
  capitalizedSubject:
    enabled: true
  wip:
    enabled: true